import Foundation

struct FontDocument: Identifiable {
    let id: UUID
    var name: String
    var glyphWidth: Int
    var glyphHeight: Int
    var glyphs: [Glyph]

    init(id: UUID = UUID(), name: String, glyphWidth: Int, glyphHeight: Int, glyphs: [Glyph]) {
        self.id = id
        self.name = name
        self.glyphWidth = glyphWidth
        self.glyphHeight = glyphHeight
        self.glyphs = glyphs
    }

    static func sample() -> FontDocument {
        var glyphs: [Glyph] = []
        let charset = Array("FontEdit".unicodeScalars.map(Character.init))

        for character in charset {
            let seed = UInt64(character.unicodeScalars.first?.value ?? 0)
            var generator = SeededGenerator(seed: seed)
            let pixels = (0..<14).map { _ in
                (0..<10).map { _ in Bool.random(using: &generator) }
            }
            glyphs.append(Glyph(character: character, pixels: pixels))
        }

        glyphs.append(Glyph.empty(width: 10, height: 14, character: " "))
        return FontDocument(name: "Sample", glyphWidth: 10, glyphHeight: 14, glyphs: glyphs)
    }
}

struct ExportOptions {
    var msbFirst: Bool = true
    var invertBits: Bool = false
    var includeLineSpacing: Bool = true
    var tabSize: Int = 4
}

extension Glyph {
    func toBytes(msbFirst: Bool, invert: Bool) -> [UInt8] {
        let bits = pixels.flatMap { $0 }
        var bytes: [UInt8] = []
        var index = 0

        while index < bits.count {
            var value: UInt8 = 0
            for bitPosition in 0..<8 {
                guard index < bits.count else { break }
                let bit = bits[index] != invert
                if msbFirst {
                    value |= bit ? 1 << (7 - bitPosition) : 0
                } else {
                    value |= bit ? 1 << bitPosition : 0
                }
                index += 1
            }
            bytes.append(value)
        }

        return bytes
    }
}

extension FontDocument {
    func exportC(options: ExportOptions) -> String {
        let tab = String(repeating: " ", count: options.tabSize)
        var lines: [String] = []

        lines.append("/* Generated by FontEdit SwiftUI prototype */")
        lines.append("const uint8_t \(name)_width = \(glyphWidth);")
        lines.append("const uint8_t \(name)_height = \(glyphHeight);")
        lines.append("const uint8_t \(name)[] = {")

        for glyph in glyphs {
            let label = glyph.character.map { "'\($0)'" } ?? "custom"
            lines.append("\(tab)// \(label)")
            let bytes = glyph.toBytes(msbFirst: options.msbFirst, invert: options.invertBits)
            let formatted = bytes.map { String(format: "0x%02X", $0) }.joined(separator: ", ")
            lines.append("\(tab)\(formatted),")
        }

        lines.append("};")
        return lines.joined(separator: "\n")
    }

    func exportPython(options: ExportOptions) -> String {
        var lines: [String] = []
        lines.append("# Generated by FontEdit SwiftUI prototype")
        lines.append("font_width = \(glyphWidth)")
        lines.append("font_height = \(glyphHeight)")
        lines.append("font_data = [")

        for glyph in glyphs {
            let label = glyph.character.map { "# '\($0)'" } ?? "# custom glyph"
            lines.append("    \(label)")
            let bytes = glyph.toBytes(msbFirst: options.msbFirst, invert: options.invertBits)
            let formatted = bytes.map { String(format: "0x%02X", $0) }.joined(separator: ", ")
            lines.append("    \(formatted),")
        }

        lines.append("]")
        return lines.joined(separator: "\n")
    }
}

private struct SeededGenerator: RandomNumberGenerator {
    private var state: UInt64

    init(seed: UInt64) {
        state = seed == 0 ? 0xCAFEBABE : seed
    }

    mutating func next() -> UInt64 {
        state ^= state << 7
        state ^= state >> 9
        state ^= 0x9E3779B97F4A7C15
        return state
    }
}
